// Songs List
export const LOAD_SONGSLIST_REQUEST = 'LOAD_SONGSLIST_REQUEST';
export const LOAD_SONGSLIST_SUCCESS = 'LOAD_SONGSLIST_SUCCESS';
export const LOAD_SONGSLIST_FAILURE = 'LOAD_SONGSLIST_FAILURE';

// Playlist
export const LOAD_PLAYLIST_REQUEST = 'LOAD_PLAYLIST_REQUEST';
export const LOAD_PLAYLIST_SUCCESS = 'LOAD_PLAYLIST_SUCCESS';
export const LOAD_PLAYLIST_FAILURE = 'LOAD_PLAYLIST_FAILURE';

// Player
export const PLAY_REQUEST = 'PLAY_REQUEST';
export const PAUSE_REQUEST = 'PAUSE_REQUEST';
export const REPLAY_REQUEST = 'REPLAY_REQUEST';
