/* Songs List */

export const SONGS_BY_ARTIST_REQUEST = 'SONGS_BY_ARTIST_REQUEST';
export const SONGS_BY_ARTIST_SUCCESS = 'SONGS_BY_ARTIST_SUCCESS';
export const SONGS_BY_ARTIST_FAILURE = 'SONGS_BY_ARTIST_FAILURE';

export const SONGS_BY_LANG_REQUEST = 'SONGS_BY_LANG_REQUEST';
export const SONGS_BY_LANG_SUCCESS = 'SONGS_BY_LANG_SUCCESS';
export const SONGS_BY_LANG_FAILURE = 'SONGS_BY_LANG_FAILURE';

export const SONGS_BY_KEYWORD_REQUEST = 'SONGS_BY_KEYWORD_REQUEST';
export const SONGS_BY_KEYWORD_SUCCESS = 'SONGS_BY_KEYWORD_SUCCESS';
export const SONGS_BY_KEYWORD_FAILURE = 'SONGS_BY_KEYWORD_FAILURE';

/* Playlist */
export const LOAD_PLAYLIST_REQUEST = 'LOAD_PLAYLIST_REQUEST';
export const LOAD_PLAYLIST_SUCCESS = 'LOAD_PLAYLIST_SUCCESS';
export const LOAD_PLAYLIST_FAILURE = 'LOAD_PLAYLIST_FAILURE';

/* Favorite */
export const SONGS_FROM_FAVORITE_REQUEST = 'SONGS_FROM_FAVORITE_REQUEST';
export const SONGS_FROM_FAVORITE_SUCCESS = 'SONGS_FROM_FAVORITE_SUCCESS';
export const SONGS_FROM_FAVORITE_FAILURE = 'SONGS_FROM_FAVORITE_FAILURE';

/* Player */
export const PLAY_REQUEST = 'PLAY_REQUEST';
export const PAUSE_REQUEST = 'PAUSE_REQUEST';
export const REPLAY_REQUEST = 'REPLAY_REQUEST';
