export const SONGS_LIST_REQUEST = 'SONGS_LIST_REQUEST';
export const SONGS_LIST_SUCCESS = 'SONGS_LIST_SUCCESS';
export const SONGS_LIST_FAILURE = 'SONGS_LIST_FAILURE';

export const PLAYLIST_REQUEST = 'PLAYLIST_REQUEST';
export const PLAYLIST_SUCCESS = 'PLAYLIST_SUCCESS';
export const PLAYLIST_FAILURE = 'PLAYLIST_FAILURE';

export const FAVORITE_REQUEST = 'FAVORITE_REQUEST';
export const FAVORITE_SUCCESS = 'FAVORITE_SUCCESS';
export const FAVORITE_FAILURE = 'FAVORITE_FAILURE';

export const PREPARE_TODO = 'PREPARE_TODO';
export const ADD_PLAY = 'ADD_PLAY';
export const INSERT_PLAY = 'INSERT_PLAY';
export const ADD_FAVORITE = 'ADD_FAVORITE';

export const PLAY_REQUEST = 'PLAY_REQUEST';
export const PLAY_SUCCESS = 'PLAY_SUCCESS';
export const PLAY_FAILURE = 'PLAY_FAILURE';

export const PAUSE_REQUEST = 'PAUSE_REQUEST';
export const PAUSE_SUCCESS = 'PAUSE_SUCCESS';
export const PAUSE_FAILURE = 'PAUSE_FAILURE';
